InfoMallWebService/Models/CustomerProduct.cs
using InfoMallWebService.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoMallWebService.Models
{
	public class CustomerProduct
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int CustomerProductId { get; set; }

		[Required]
		public string CustomerDecription { get; set; }

		public bool CustomerHasPaid { get; set; }

		public string ExtraInformation { get; set; }

		public DateTime ExpectedStartDate { get; set; }
		public DateTime ExpectedEndDate { get; set; }
		public DateTime ActualStartDate { get; set; }
		public DateTime ActualEndDate { get; set; }

		public ProductStage Stage { get; set; }

		public PaymentType PaymentType { get; set; }

		[ForeignKey("CustomerId")]
		public Customer Customer { get; set; }
		public string CustomerId { get; set; }
	}
}

InfoMallWebService/Controllers/CustomerProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoMallWebService.Data;
using InfoMallWebService.Dtos;
using InfoMallWebService.Models;
using InfoMallWebService.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace InfoMallWebService.Controllers
{
    public class CustomerProductsController : Controller
    {
        private readonly ICustomerProductRepository _cust;
        private readonly ApplicationDbContext _ctx;
        public CustomerProductsController(ICustomerProductRepository customer, ApplicationDbContext context)
        {
            _cust = customer;
            _ctx = context;
        }
        // GET: PromotionCustomers
        public async Task<IActionResult> Index()
        {
            var model = await _cust.GetAllCustomerProducts();
            return View(model);
        }

        // GET: PromotionCustomers/Details/5
        public async Task<IActionResult> Details()
        {
            var model = await _cust.GetAllCustomerProducts();

            return View(model);
        }

        // GET: PromotionCustomers/Create
        public ActionResult Create()
        {
            ViewData["Category"] = new SelectList(_ctx.ContentsForTab.Include(c => c.Category).Where(c => c.Category.CategoryName.ToLower() == "services"), "Title", "Title", "Software Development");
            return View();
        }

        // POST: PromotionCustomers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustumerProductDto customerProduct)
        {
            if (!ModelState.IsValid)
            {
                return View("Error", "Home");
            }
            try
            {
                var result = await _cust.AddCustomerProduct(customerProduct);

                if (result.Item1)
                {
                    if (result.Item2)
                    {
                        ViewData["Success"] = "Mail Sent";
                    }
                    else
                    {
                        ViewData["Success"] = "Not Sent";
                    }
                    return RedirectToAction(nameof(Details));
                }

                return View("Error", "Home");
            }
            catch
            {
                return View("Error", "Home");
            }
        }

        // GET: PromotionCustomers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _cust.GetCustomerProductById(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: PromotionCustomers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CustomerProduct customerProduct)
        {
            if (id != customerProduct.CustomerProductId)
            {
                return RedirectToAction("Edit", new { id });
            }
            try
            {
                await _cust.UpdateCustomerProductWithId(customerProduct);
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error", "Home");
            }
        }

        // GET: PromotionCustomers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _cust.GetCustomerProductById(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: PromotionCustomers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                _cust.DeleteCustomerProductWithId(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error", "Home");
            }
        }
    }
}

InfoMallWebService/Views/CustomerProducts/Create.cshtml
@using Microsoft.AspNetCore.Identity
@model InfoMallWebService.Dtos.CustumerProductDto


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@{
    string userId = null;
    int i = 1;
    if (SignInManager.IsSignedIn(User))
    {

        ApplicationUser user = await UserManager.GetUserAsync(User);
        userId = user.Id;
    }
}

<!-- //contact info -->
<div class="serives-agile py-5">
    <div class="">
        <h1 class="about-header mt-4 text-center">Request Form</h1>
    </div>
    <div class="container py-xl-5 py-lg-3">
        <div class="col-md-12 main_grid_contact bg-light">

            <!-- -->
            <div class="form form_contact">

                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserId" value="@userId" />
                    <div class="form-group" id="service">
                        <label asp-for="Service" class="control-label">Please choose a service</label>
                        <div class="styled-select slate">
                            <select asp-for="Service" class="form-control" asp-items="ViewBag.Category"></select>
                            <span asp-validation-for="Service" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerDecription" class="mb-2 control-label">Message</label>
                        <textarea asp-for="CustomerDecription" class="form-control"></textarea>
                        <span asp-validation-for="CustomerDecription" class="text-danger"></span>
                    </div>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div class="form-group">
                            <input type="submit" value="Submit" class="btn btn-primary" />
                        </div>
                    }
                    else
                    {
                        <div class="submit">
                            <a class=" sign-up popup-with-zoom-anim" asp-action="Login" asp-controller="Account" asp-route-returnUrl="@Url.Action("Create", "CustomerProducts")">Submit</a>
                        </div>
                    }
                </form>

            </div>
        </div>
    </div>
</div>
<!-- //contact -->



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoMallWebService/Views/CustomerProducts/Details.cshtml
@model IEnumerable<InfoMallWebService.Models.CustomerProduct>


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    Layout = "~/Views/Manage/_Layout.cshtml";
    ViewData["Title"] = "Details";
    ViewData.AddActivePage(ManageNavPages.CustomerProduct);
    ViewData["Success"] = null;
    string userId = null;
    if (SignInManager.IsSignedIn(User))
    {
        ApplicationUser user = await UserManager.GetUserAsync(User);
        userId = user.Id;
    }
}

<div class="row">
    <h2 class="col-md-12">Available Promotions</h2>

    @if (ViewBag.Success != null)
    {
        <p>@ViewBag.Success.ToString()</p>
    }
    <div class="col-md-6 font-size-12">
        @foreach (var item in Model.Where(p => p.Customer.UserId == userId))
        {
            <div class="mt-4">
                <span>@item.CustomerDecription</span>
                @if (item.CustomerHasPaid)
                {
                    <p>Expected Start Date: @item.ExpectedStartDate</p>
                    <p>Expected Start Date: @item.ExpectedStartDate</p>
                }
                else
                {
                    <input type="button" class="btn btn-primary" value="Pay" />
                }
            </div>
        }

    </div>
</div>

InfoMallWebService/Views/CustomerProducts/Index.cshtml
@model IEnumerable<InfoMallWebService.Models.CustomerProduct>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerDecription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerHasPaid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExtraInformation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedStartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualStartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerDecription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerHasPaid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExtraInformation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CustomerProductId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CustomerProductId })
            </td>
        </tr>
}
    </tbody>
</table>