InfoMallWebService/Controllers/CategoryForInfosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using InfoMallWebService.Repository;
using InfoMallWebService.Models;

namespace InfoMallWebService.Controllers
{
    public class CategoryForInfosController : Controller
    {
        private readonly ICategoryForInfoRepository _cat;
        public CategoryForInfosController(ICategoryForInfoRepository category)
        {
            _cat = category;
        }
        // GET: CategoryForInfos
        public async Task<IActionResult> Index()
        {
            var model = await _cat.GetAllCategories(false);
            return View(model);
        }

        // GET: CategoryForInfos/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _cat.GetCategoryById(id, true);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // GET: ContentsForInfos/Mall
        public async Task<IActionResult> Mall()
        {
            var model = await _cat.GetAllCategories(true);
            return View(model);
        }

        // GET: CategoryForInfos/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: CategoryForInfos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryForInformation category)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                await _cat.AddCategory(category);
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: CategoryForInfos/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _cat.GetCategoryById(id, false);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: CategoryForInfos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CategoryForInformation category)
        {
            if (id != category.CategoryId)
            {
                return RedirectToAction("Error", "Home");
            }
            if(!ModelState.IsValid)
            {
                return View("Edit", new { id });
            }
            try
            {
                await _cat.UpdateCategoryById(category);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: CategoryForInfos/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _cat.GetCategoryById(id, false);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: CategoryForInfos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                _cat.DeleteCategoryById(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

InfoMallWebService/Views/CategoryForInfos/Create.cshtml
@model InfoMallWebService.Models.CategoryForInformation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CategoryForInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryInformation" class="control-label"></label>
                <input asp-for="CategoryInformation" class="form-control" />
                <span asp-validation-for="CategoryInformation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoMallWebService/Views/CategoryForInfos/Delete.cshtml
@model InfoMallWebService.Models.CategoryForInformation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoryForInformation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryInformation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryInformation)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@Model.CategoryId">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InfoMallWebService/Views/CategoryForInfos/Details.cshtml
@model InfoMallWebService.Models.CategoryForInformation

@inject ICategoryForInfoRepository Categories

@{
    ViewData["Title"] = "Details";
    List<ContentForMall> contentsTrending = new List<ContentForMall>();
    List<ContentForMall> contentsRecent = new List<ContentForMall>();
    var cats = await Categories.GetAllCategories(true);
}



<!-- single -->
<section class="banner-bottom py-5">
    <div class="container py-xl-5 py-lg-3">
        <div class="inner-sec">
            <div class="row">
                <!-- left side -->
                <div class="col-lg-8 left-blog-info text-left no-padding-left-blog">
                    @foreach (var content in Model.ContentsForInformation)
                    {
                    <a class="single-text text-dark font-weight-light" asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId">
                        <div class="col-md-12 no-padding-left-blog">
                            <div class="row">
                                <h2 class="col-md-12 blog-h-font mb-3">@content.Title</h2>
                                <div class="col-md-4">
                                    <img src="~/@content.ImagePath" alt="@content.Title" class="img-responsive" />
                                </div>
                                <div class="col-md-8">
                                    <div class="row">
                                        <p class="col-md-12 font-size-16 blog-p-font">@content.ShortDescription</p>
                                        <p class="col-md-12 font-size-12 blog-p-font">
                                            <strong>Date Posted:</strong> @content.DatePosted.ToShortDateString()<br />
                                            <strong>Number of Views:</strong> @content.NumberOfViews
                                        </p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </a>


                        if (content.NumberOfViews > 2)
                        {
                            contentsTrending.Add(content);
                        }
                        if (DateTime.Now - content.DatePosted <= TimeSpan.FromDays(2))
                        {
                            contentsRecent.Add(content);
                        }

                    }
                    
                </div>
                <!-- //left side -->
                <!-- right side -->
                <aside class="col-lg-4 right-blog-con text-right">
                    <div class="right-blog-info text-left">
                        
                        <div class="tech-btm">
                            <h4>Categories</h4>
                            <ul class="list-group single">
                                @foreach (var category in cats)
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a asp-action="Details" asp-controller="CategoryForInfos" asp-route-id="@category.CategoryId">@category.CategoryName</a> 
                                        <span class="badge badge-primary badge-pill">@category.ContentsForInformation.Count().ToString()</span>
                                    </li>
                                }
                            </ul>
                        </div>
                        <div class="tech-btm">
                            <h4>Top stories of the week</h4>
                            @foreach (var content in contentsTrending)
                            {
                                <div class="blog-grids row mb-3">
                                    <div class="col-md-5 blog-grid-left">
                                        <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                            <img src="~/@content.ImagePath" class="img-fluid rounded" alt="@content.ImagePath">
                                        </a>
                                    </div>
                                    <div class="col-md-7 blog-grid-right">
                                        <h5>
                                            <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                @content.ShortDescription
                                            </a>
                                            
                                        </h5>
                                        <div class="sub-meta">
                                            <span>
                                                <i class="far fa-clock"></i> @content.DatePosted.ToLongDateString()
                                            </span>
                                        </div>
                                    </div>

                                </div>
                            }

                            
                        </div>

                        <div class="single-gd tech-btm">
                            <h4>Recent Post</h4>
                            <div class="blog-grids">
                                @foreach (var content in contentsRecent)
                                {
                                    <div class="blog-grids row mb-3">
                                        <div class="col-md-5 blog-grid-left">
                                            <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                <img src="~/@content.ImagePath" class="img-fluid rounded" alt="@content.ImagePath">
                                            </a>
                                        </div>
                                        <div class="col-md-7 blog-grid-right">
                                            <h5>
                                                <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                    @content.ShortDescription
                                                </a>

                                            </h5>
                                            <div class="sub-meta">
                                                <span>
                                                    <i class="far fa-clock"></i> @content.DatePosted.ToShortDateString()
                                                </span>
                                            </div>
                                        </div>

                                    </div>
                                }
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                </aside>
                <!-- //right side -->
            </div>

        </div>
    </div>
</section>
<!-- //single -->

InfoMallWebService/Views/CategoryForInfos/Edit.cshtml
@model InfoMallWebService.Models.CategoryForInformation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CategoryForInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.CategoryId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryInformation" class="control-label"></label>
                <input asp-for="CategoryInformation" class="form-control" />
                <span asp-validation-for="CategoryInformation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoMallWebService/Views/CategoryForInfos/Index.cshtml
@model IEnumerable<InfoMallWebService.Models.CategoryForInformation>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryInformation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryInformation)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CategoryId }) |
                @Html.ActionLink("Details", "Details", new { id = item.CategoryId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CategoryId })
            </td>
        </tr>
}
    </tbody>
</table>

InfoMallWebService/Views/CategoryForInfos/Mall.cshtml
@model IEnumerable<InfoMallWebService.Models.CategoryForInformation>

@{
    ViewData["Title"] = "Details";
    int i = 1;
    List<ContentForMall> contentsTrending = new List<ContentForMall>();
    List<ContentForMall> contentsRecent = new List<ContentForMall>();
    List<ContentForMall> otherNews = new List<ContentForMall>();
}



<!-- single -->
<section class="banner-bottom py-5">
    <div class="container py-xl-5 py-lg-3">
        <div class="inner-sec">

            <h3 class="tittle text-center text-uppercase text-dark font-weight-bold mb-sm-5 mb-4">Information Mall</h3>
            <div class="row">
                <!-- left side -->
                <div class="col-lg-8 left-blog-info text-left no-padding-left-blog">
                    @foreach (var item in Model)
                    {
                        foreach (var content in item.ContentsForInformation)
                        {
                            if (i == 1)
                            {
                                <a class="single-text text-dark font-weight-light" asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId">
                                    <div class="col-md-12 no-padding-left-blog">
                                        <div class="row">
                                            <h2 class="col-md-12 blog-h-font mb-3">@content.Title</h2>
                                            <div class="col-md-4">
                                                <img src="~/@content.ImagePath" alt="@content.Title" class="img-responsive" />
                                            </div>
                                            <div class="col-md-8">
                                                <div class="row">
                                                    <p class="col-md-12 font-size-16 blog-p-font">@content.ShortDescription</p>
                                                    <p class="col-md-12 font-size-12 blog-p-font">
                                                        <strong>Date Posted:</strong> @content.DatePosted.ToShortDateString()<br />
                                                        <strong>Number of Views:</strong> @content.NumberOfViews
                                                    </p>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </a>

                            }
                            else
                            {
                                otherNews.Add(content);

                            }
                            if (content.NumberOfViews > 2)
                            {
                                contentsTrending.Add(content);
                            }
                            if (DateTime.Now - content.DatePosted <= TimeSpan.FromDays(2))
                            {
                             
                                contentsRecent.Add(content);
                            }
                            i++;
                        }

                    }

                </div>
                <!-- //left side -->
                <!-- right side -->
                <aside class="col-lg-4 right-blog-con text-right">
                    <div class="right-blog-info text-left padding-right-blog">
                        <div class="category-story tech-btm">
                            <h4>More Stories</h4>
                            <ul class="list-unstyled">
                                @foreach (var content in otherNews.Take(4))
                                {
                                    <li class="border-bottom mb-3 pb-3">
                                        <i class="fas fa-angle-right mr-2"></i>
                                        <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">@content.ShortDescription</a>
                                    </li>
                                }
                            </ul>
                        </div>


                        <div class="tech-btm">
                            <h4>Categories</h4>
                            <ul class="list-group single">
                                @foreach (var category in Model)
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a asp-action="Details" asp-controller="CategoryForInfos" asp-route-id="@category.CategoryId">@category.CategoryName</a>
                                        <span class="badge badge-primary badge-pill">@category.ContentsForInformation.Count().ToString()</span>
                                    </li>
                                }
                            </ul>
                        </div>
                        <div class="tech-btm">
                            <h4>Top stories of the week</h4>
                            @foreach (var content in contentsTrending)
                            {
                                <div class="blog-grids row mb-3">
                                    <div class="col-md-5 blog-grid-left">
                                        <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                            <img src="~/@content.ImagePath" class="img-fluid rounded" alt="@content.ImagePath">
                                        </a>
                                    </div>
                                    <div class="col-md-7 blog-grid-right">
                                        <h5>
                                            <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                @content.ShortDescription
                                            </a>

                                        </h5>
                                        <div class="sub-meta">
                                            <span>
                                                <i class="far fa-clock"></i> @content.DatePosted.ToLongDateString()
                                            </span>
                                        </div>
                                    </div>

                                </div>
                            }


                        </div>

                        <div class="single-gd tech-btm">
                            <h4>Recent Post</h4>
                            <div class="blog-grids">
                                @foreach (var content in contentsRecent)
                                {
                                    <div class="blog-grids row mb-3">
                                        <div class="col-md-5 blog-grid-left">
                                            <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                <img src="~/@content.ImagePath" class="img-fluid rounded" alt="@content.ImagePath">
                                            </a>
                                        </div>
                                        <div class="col-md-7 blog-grid-right">
                                            <h5>
                                                <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                    @content.ShortDescription
                                                </a>

                                            </h5>
                                            <div class="sub-meta">
                                                <span>
                                                    <i class="far fa-clock"></i> @content.DatePosted.ToShortDateString()
                                                </span>
                                            </div>
                                        </div>

                                    </div>
                                }
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                </aside>
                <!-- //right side -->
            </div>

        </div>
    </div>
</section>
<!-- //single -->