InfoMallWebService/Models/Promotion.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoMallWebService.Models
{
	public class Promotion
	{
		[Key]
		public int PromotionId { get; set; }

		[Required]
		public string PromotionName { get; set; }
		public string PromotionExtra { get; set; }
		public string PromotionDescription { get; set; }

		public bool PromotionAvailable { get; set; }

		[DataType(DataType.ImageUrl)]
		public string ImagePath { get; set; }

		[ForeignKey("CategoryForTabId")]
		public CategoryForTab Category { get; set; }
		public int CategoryForTabId { get; set; }
		
		public ICollection<PromotionInformation> PromotionsInformation { get; set; }
		public ICollection<PromotionCustomer> PromotionCustomers { get; set; }
	}
}

InfoMallWebService/Controllers/ContentForTabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoMallWebService.Data;
using InfoMallWebService.Dtos;
using InfoMallWebService.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InfoMallWebService.Controllers
{
    public class ContentForTabsController : Controller
    {
		private readonly IContentForTabRepository _con;
		private readonly ApplicationDbContext _ctx;
		public ContentForTabsController(IContentForTabRepository con,
			ApplicationDbContext context)
		{
			_con = con;
			_ctx = context;
		}
        // GET: ContentForTabs
        public async Task<ActionResult> Index()
        {
			var model = await _con.GetAllContents(false);
            return View(model);
        }

        // GET: ContentForTabs/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _con.GetContentByID(id, true);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // GET: ContentForTabs/Create
        public ActionResult Create()
        {
			ViewData["Category"] = new SelectList(_ctx.CategoriesForTab, "CategoryId", "CategoryName");
			return View();
        }

        // POST: ContentForTabs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ContentForTabDto content)
        {
			if (!ModelState.IsValid)
			{
				return RedirectToAction();
			}
            try
            {
				await _con.AddContent(content);
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
				return RedirectToAction("Error", "Home");
			}
        }

        // GET: ContentForTabs/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
			var model = await _con.GetContentByID(id, true);
            if (model == null)
            {
                return NotFound();
            }
            ViewData["Category"] = new SelectList(_ctx.CategoriesForTab, "CategoryId", "CategoryName", id);
			return View(model);
        }

        // POST: ContentForTabs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ContentForTabDto content)
        {
			if (!ModelState.IsValid)
			{
				return RedirectToAction("Edit", new { id });
			}
			if (id != content.ContentId)
			{
				return RedirectToAction("Edit", new { id });
			}
			try
            {
				await _con.UpdateContentWithID(content);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
			}
        }

        // GET: ContentForTabs/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
			var model = await _con.GetContentByID(id, false);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
		}

        // POST: ContentForTabs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id, ContentForTabDto content)
        {
			if (!ModelState.IsValid)
			{
				return RedirectToAction("Delete", new { id });
			}
			if (id != content.ContentId)
			{
				return RedirectToAction("Delete", new { id });
			}
            try
            {
				await _con.DeleteContentWithID(content);
				
				return RedirectToAction(nameof(Index));
				
			}
            catch
            {
				return RedirectToAction("Error", "Home");

			}
		}
    }
}

InfoMallWebService/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoMallWebService.Data;
using InfoMallWebService.Dtos;
using InfoMallWebService.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InfoMallWebService.Controllers
{
    public class PromotionsController : Controller
    {
        private readonly IPromotionRepository _promo;
        private readonly ApplicationDbContext _ctx;

        public PromotionsController(IPromotionRepository promo,
            ApplicationDbContext context)
        {
            _promo = promo;
            _ctx = context;
        }
        // GET: Promotions
        public async Task<ActionResult> Index()
        {
            var model = await _promo.GetAllPromotions(true, true);
            return View(model);
        }

        // GET: Promotions/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _promo.GetPromotionById(id, true, true);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // GET: Promotions/Create
        public ActionResult Create()
        {
            ViewData["Category"] = new SelectList(_ctx.CategoriesForTab, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Promotions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(bool sendToAll, PromotionDto promotion)
        {
            if(!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }
            try
            {
                var result = await _promo.AddPromotion(promotion, sendToAll);
                if(result.Item1)
                {
                    if(result.Item2)
                    {
                        ViewData["Mail"] = "Success";
                    }
                    else
                    {
                        ViewData["Mail"] = "Failure";
                    }
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction("Create");
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: Promotions/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _promo.GetPromotionById(id, true, false);
            if (model == null)
            {
                return NotFound();
            }
            ViewData["Category"] = new SelectList(_ctx.CategoriesForTab, "CategoryId", "CategoryName", id);
            return View(model);
        }

        // POST: Promotions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, PromotionDto promotion)
        {
            if(id != promotion.PromotionId)
            {
                return RedirectToAction("Edit", new { id });
            }
            if(!ModelState.IsValid)
            {
                return RedirectToAction("Edit", new { id });
            }
            try
            {
                bool result = await _promo.UpdatePromotionWithId(promotion);
                if(result)
                {
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction("Edit", new { id });

            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: Promotions/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _promo.GetPromotionById(id, true, false);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: Promotions/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                await _promo.DeletePromotionWithId(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

InfoMallWebService/Views/Shared/_AboutUs.cshtml
@model InfoMallWebService.Models.CategoryForTab


<div class="mt-8"></div>
@foreach (var about in Model.ContentForTabs.Take(1))
{
    <!-- banner bottom -->
    <div class="middle-agile-3">
        <div class="container">
            <div class="d-flex mt-4">
                <div>
                    <h1 class="about-header margintop4">About Us</h1>
                    <h3 class="next-header mt-4">@Model.ContentForTabs.ElementAt(0).Title</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 about-info-sec py-5">
                    <div class="py-xl-4 py-sm-3 py-2 no_paddingtop">
                        <p class="whats-text text-justify">
                            @Html.Raw(Model.ContentForTabs.ElementAt(0).LongDescription)
                        </p>
                    </div>
                </div>
                <div class="col-md-6"><img src="~/@Model.ContentForTabs.ElementAt(0).ImagePath" alt="@Model.ContentForTabs.ElementAt(0).Title" class="img-fluid" /></div>

            </div>
        </div>
    </div>
}


    <div class="subscribe-info-w3l">
        <div class="container py-lg-3 paddingbottomhalf">

            <h3 class="next-header">Company Profile</h3>

        </div>
    </div>
    <div class="middle-agile-3 no_margintop">
        <div class="container">
            <div class="row">

                <div class="col-md-6"><img src="~/@Model.ContentForTabs.Skip(1).Take(1).SingleOrDefault().ImagePath" alt="@Model.ContentForTabs.Skip(1).Take(1).SingleOrDefault().Title" class="img-fluid" /></div>
                <div class="col-md-6 about-info-sec ">
                    <div class="py-xl-4 py-sm-3 py-2">
                        <p class="whats-text mb-4 text-justify">@Model.ContentForTabs.Where(c => c.Title.ToLower() == "company profile").SingleOrDefault().LongDescription</p>
                        @foreach (var item in Model.ContentForTabs.Skip(1))
                        {
                            if (item.Title.ToLower() != "company profile")
                            {
                                <h3 class="what-title text-dark">@item.Title</h3>
                                <p class="whats-text mb-4 text-justify padding-right-15">@item.LongDescription</p>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- subscribe -->
        <div class="subscribe-info-w3l text-center py-5 customer-product">
            <div class="container py-xl-5 py-lg-3">

                <p class="mb-5 text-white">
                    We would be glad to spice up your tech.
                </p>
                <a asp-action="Create" asp-controller="CustomerProducts">Get in Touch</a>

            </div>
        </div>
</div>

InfoMallWebService/Views/Shared/_Layout.cshtml
@inject ICategoryForTabRepository category
@{
	List<CategoryForTab> tabs = await category.GetAllCategories(false, false);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8" />
    <meta name="keywords" content="InfoMall Nigeria Limited, Technology, Tech Nigeria" />
    <title>@ViewData["Title"] - InfoMallWebService</title>
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/fontawesome-all.css" />
        <link rel="stylesheet" href="~/css/login.css" />
        <link rel="stylesheet" href="~/css/owl.carousel.css" />
        <link rel="stylesheet" href="~/css/owl.theme.css" />
        <link rel="stylesheet" href="~/css/prettyPhoto.css" />
        <link rel="stylesheet" href="~/css/pricing.css" />
        <link rel="stylesheet" href="~/css/single.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />

    <!-- Web-Fonts -->
    <link href="//fonts.googleapis.com/css?family=Archivo+Black&amp;subset=latin-ext" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Amaranth:400,400i,700,700i" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- //Web-Fonts -->

</head>
<body>
	<!-- header -->
	<header>

		<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
			<a class="navbar-brand" asp-action="Index" asp-controller="Home">
				<img src="~/@Startup.Configuration["SelfInformation:LogoUrl"]" class="logo img-fluid" alt="InfoMall logo identity">
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-toggle" aria-controls="navbarNavAltMarkup"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
            <div class="collapse navbar-collapse navbar-toggle " id="navbarNavAltMarkup">
                <ul class="navbar-nav ml-auto">
                    <li>
                        <a class="nav-link active" asp-action="Index" asp-controller="Home">Home</a>
                    </li>
                    @foreach (CategoryForTab tab in tabs)
                    {
                        if (tab.CategoryName.ToLower() == "promotions")
                        {
                            <li class="negative-margin-top-5">
                                <a class="nav-link promo-button" asp-action="Details" asp-controller="CategoryForTabs" asp-route-id="@tab.CategoryId">@tab.CategoryName</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link" asp-action="Details" asp-controller="CategoryForTabs" asp-route-id="@tab.CategoryId">@tab.CategoryName</a>
                            </li>
                        }

                    }
                    <li>
                        <a class="nav-link" asp-action="Contact" asp-controller="Home">Contact Us</a>
                    </li>
                    <partial name="~/Views/Shared/_LoginPartial.cshtml" />
                </ul>
                
            </div>
		</nav>
	</header>
	<!-- //header -->
	@*<partial name="_CookieConsentPartial" />*@
	@RenderBody()


	<!-- footer -->
	<footer>
		<div class="w3ls-footer-grids py-sm-4 py-3">
			<div class="container py-xl-5 py-sm-3">
				<div class="row">
					<div class="col-lg-3 col-sm-6 w3l-footer">
						<ul class="list-unstyled">
							<li>
								<a asp-action="Index" asp-controller="Home">Home</a>
							</li>
							@foreach (CategoryForTab tab in tabs)
							{
								<li class="mt-2">
									<a asp-action="Details" asp-controller="CategoryForTabs" asp-route-id="@tab.CategoryId" class="">@tab.CategoryName</a>
								</li>
							}



						</ul>
					</div>
					<div class="col-lg-3 col-sm-6 w3l-footer mt-sm-0 mt-2">
						<ul class="list-unstyled">
							<li class="mt-2">
								<a asp-action="Contact" asp-controller="Home" class="">Contact Us</a>
							</li>
							<li class="mt-2">
								<a asp-action="Mall" asp-controller="CategoryForInfos" class="">Information Mall</a>
							</li>
							<li class="mt-2">
								<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-sm-6 w3l-footer footer-social-agile mt-lg-0 mt-4">
						<h1 class="footer-head-w3ls mb-4">Connect with us</h1>
						<ul class="list-unstyled">
							<li>
								<a href="@Startup.Configuration["SelfInformation:Facebook"]">
									<i class="fab fa-facebook-f"></i>
								</a>
							</li>
							<li class="mx-1">
								<a href="@Startup.Configuration["SelfInformation:Twitter"]">
									<i class="fab fa-twitter"></i>
								</a>
							</li>
							<li>
								<a href="@Startup.Configuration["SelfInformation:Instagram"]">
									<i class="fab fa-instagram"></i>
								</a>
							</li>
							<li class="ml-1">
								<a href="@Startup.Configuration["SelfInformation:LinkedIn"]">
									<i class="fab fa-linkedin"></i>
								</a>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-sm-6 w3l-footer payment-w3lsmk  mt-lg-0 mt-4">
						<h2 class="footer-head-w3ls mb-4">Payment Options</h2>
						<ul class="list-unstyled">

							<li class="mx-1">
								<a href="#">
									<i class="fab fa-cc-visa"></i>
								</a>
							</li>
							<li class="">
								<a href="#">
									<i class="fab fa-cc-paypal"></i>
								</a>
							</li>
							<li class="mx-1">
								<a href="#">
									<i class="fab fa-cc-stripe"></i>
								</a>
							</li>

							<li class="ml-1">
								<a href="#">
									<i class="fab fa-cc-mastercard"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- //footer -->
	<!-- copyright -->
	<div class="copy-right-w3ls py-3">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 w3ls-left-copy text-lg-left text-center">
					<p class="copy-right-grids text-white">
						&copy; @DateTime.Now.Year InfoMall | Nigeria

					</p>
				</div>
				<div class="col-lg-4 w3ls-left-copy text-lg-right text-center">
					<p class="text-white">
						<i class="fas fa-phone mr-2"></i> @Startup.Configuration["SelfInformation:Telephone"]
					</p>
				</div>
			</div>
		</div>
	</div>
	<!-- //copyright -->

	<environment include="Development">
		@*<script src="~/lib/jquery/dist/jquery.js"></script>
			<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>*@

		<script src="~/js/jquery-2.2.3.min.js"></script>
		<script src="~/js/bootstrap.js"></script>

	</environment>
	<environment exclude="Development">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
		</script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
		</script>
	</environment>




	<script>
		$(document).ready(function () {
			$(".dropdown").hover(
				function () {
					$('.dropdown-menu', this).stop(true, true).slideDown("fast");
					$(this).toggleClass('open');
				},
				function () {
					$('.dropdown-menu', this).stop(true, true).slideUp("fast");
					$(this).toggleClass('open');
				}
			);
		});
	</script>
	<!-- //dropdown smooth -->
	<!-- fixed nav -->
	<script>
		$(window).scroll(function () {
			if ($(document).scrollTop() > 50) {
				$('nav').addClass('shrink');
			} else {
				$('nav').removeClass('shrink');
			}
		});
	</script>
	<!-- //fixed nav -->
	<!-- //navigation -->
	
	<script src="~/js/SmoothScroll.min.js"></script>
	<!-- move-top -->
	<script src="~/js/move-top.js"></script>
	<!-- easing -->
	<script src="~/js/easing.js"></script>
	<!--  necessary snippets for few javascript files -->
	<script src="~/js/outdoor.js"></script>

	<script src="~/js/bootstrap.js"></script>
	<!-- Necessary-JavaScript-File-For-Bootstrap -->
	@RenderSection("Scripts", required: false)
</body>
</html>

InfoMallWebService/Views/Shared/_Product.cshtml
@model InfoMallWebService.Models.CategoryForTab

@inject ICategoryForTabRepository _cat;

@if (Model.ContentForTabs.Count() > 0)
{

    <!-- products -->
    <div class="serives-agile py-5">
        <div class="container py-xl-5 py-lg-3">
            <div class="d-flex mt-4">
                <div class="">
                    <h1 class="about-header margintop4">InfoMall Nigeria</h1>
                    <h3 class="next-header mt-4">Best Product in the world</h3>
                </div>
            </div>
            <p>@Model.CategoryInformation</p>


            <div class="d-flex no-margin-web row welcome-bottom text-center">
                @foreach (var item in Model.ContentForTabs)
                {
                    <div class="text-align col-md-6 product-img no_padding5">
                        <a asp-action="Details" asp-controller="ContentForTabs" asp-route-id="@item.ContentId">
                            <img src="~/@item.ImagePath" alt="@item.Title" class="img-fluid" />
                            <div class="product-name"><h3>@item.Title</h3></div>
                            <div class="service-offered">@item.ShortDescription</div>
                        </a>

                    </div>


                }
            </div>
        </div>
    </div>
}

@{
    //Grabing Promotions
    var promotions = await _cat.GetAllCategories();
    var promotion = promotions.SingleOrDefault(t => t.CategoryName.ToLower() == "promotions");
}
@if (promotion != null)
{
    <!--promo section-->
    <div class="middle-agile-2 bg-infomallblue">
        <div class="container ppy-lg-3">
            <div class="row">
                <div class="col-md-5">
                    <h2 class="what-title text-dark paddingtop4rem bold">@promotion.Promotions.SingleOrDefault().PromotionName</h2>
                    <p class="whats-text mb-4 text-white">
                        @promotion.Promotions.SingleOrDefault().PromotionDescription
                    </p>

                    <a asp-action="Details" asp-controller="CategoryForTabs" asp-route-id="@promotion.Promotions.SingleOrDefault().CategoryForTabId" class="btn button-style-wthree mt-sm-5 mt-4">Get Started</a>


                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-12"><img src="~/@promotion.Promotions.SingleOrDefault().ImagePath" alt="@promotion.Promotions.SingleOrDefault().PromotionName" class="img-fluid" /></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- //end of promo section -->

}

InfoMallWebService/Views/Shared/_Promotions.cshtml
@using Microsoft.AspNetCore.Identity
@model InfoMallWebService.Models.CategoryForTab

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@{
    string userId = null;
    int i = 1;
    if (SignInManager.IsSignedIn(User))
    {

        ApplicationUser user = await UserManager.GetUserAsync(User);
        userId = user.Id;
    }
}



@if (Model.Promotions != null)
{
    <div class="serives-agile py-5">
        <div class="container py-xl-5 py-lg-3">
            <div class="">
                <h1 class="about-header margintop4">@Model.Promotions.FirstOrDefault().PromotionName</h1>
                <h3 class="next-header mt-4">@Model.Promotions.FirstOrDefault().PromotionExtra</h3>
            </div>
            <div class="row">
                <div class="col-md-6 mt-4">
                    <p>@Model.Promotions.FirstOrDefault().PromotionDescription</p>

                </div>
                <div class="col-md-6 mt-4">
                    <a href="#">
                        <div class=" no_margintop">
                            <img src="~/@Model.Promotions.FirstOrDefault().ImagePath" alt="@Model.Promotions.FirstOrDefault().PromotionName" class="img-fluid" />
                        </div>

                    </a>

                </div>

            </div>

            <div class="row">
                <div class="main col-md-12">
                    
                    <div class="padding-w3l">
                        <h1>Golden Price Table</h1>
                        <div class="content">


                            @foreach (var item in Model.Promotions.FirstOrDefault().PromotionsInformation)
                            {
                                <div class="@($"grid{i}")">
                                    @Html.Raw(item.PromotionInformationContent)
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <div class="submit">
                                            <form asp-action="Create" asp-controller="PromotionCustomers">
                                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                                <input type="hidden" name="UserId" value="@userId" />
                                                <input type="hidden" name="PromotionId" value="@item.PromotionId" />
                                                <input type="hidden" name="CustomersWant" value='@($"{Model.Promotions.FirstOrDefault().PromotionName} {item.Title}")' />
                                                <input type="submit" value="Subscribe" class="sign-up popup-with-zoom-anim" />
                                            </form>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="submit">
                                            <a class=" sign-up popup-with-zoom-anim" asp-action="Login" asp-controller="Account" asp-route-returnUrl="@Url.Action("Details", "CategoryForTabs", new { id = Model.CategoryId })">Sign Up</a>
                                        </div>
                                    }

                                </div>
                                i++;
                            }
                            <div class="clear"> </div>
                        </div>



                    </div>
                    

                </div>


            </div>



        </div>
    </div>
}


<!-- services -->

InfoMallWebService/Views/Shared/_Services.cshtml
@model InfoMallWebService.Models.CategoryForTab


@if (Model.ContentForTabs.Count() > 0)
{
    <div class="serives-agile py-5">
        <div class="container py-xl-5 py-lg-3">
            <div class="d-flex mt-4">
                <div class="">
                    <h1 class="about-header margintop4">Our Services</h1>
                    <h3 class="next-header mt-4">When you say top-notch, you know it</h3>
                </div>
            </div>
            <p>@Model.CategoryInformation</p>

            <div class="row">
                @foreach (var item in Model.ContentForTabs)
                {
                    <div class="col-md-6 mt-4">
                        <div class="welcome-grid zero_padding no-margin-left no-margin-right" id="service_main">
                            <img src="~/@item.ImagePath" alt="@item.Title" class="full-width img-fluid" />
                            <h4 class="my-3">@item.Title</h4>
                            <p class="service_desc">
                                @item.LongDescription
                            </p>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
    <!-- subscribe -->
    <div class="subscribe-info-w3l text-center py-5 customer-product">
        <div class="container py-xl-5 py-lg-3">

            <p class="mb-5 text-white">
                We would be glad to spice up your tech.
            </p>
            <a asp-action="Create" asp-controller="CustomerProducts">Get in Touch</a>

        </div>
    </div>
}