InfoMallWebService/Models/ContentForMall.cs
using InfoMallWebService.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoMallWebService.Models
{
	public class ContentForMall
	{
		[Key]
		public int ContentId { get; set; }
		[Required]
		public string Title { get; set; }
		[Required]
		public string ShortDescription { get; set; }
		[Required]
		[DataType(DataType.Html)]
		public string LongDescription { get; set; }
		public int NumberOfViews { get; set; }
		public bool ShowOnHome { get; set; }
		public DateTime DatePosted { get; set; }
		[DataType(DataType.ImageUrl)]
		public string ImagePath { get; set; }
		public ContentMallPosition Position { get; set; }
		[ForeignKey("CategoryForInformationId")]
		public CategoryForInformation Category { get; set; }
		public int CategoryForInformationId { get; set; }
	}
}

InfoMallWebService/Controllers/ContentForMallsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoMallWebService.Data;
using InfoMallWebService.Dtos;
using InfoMallWebService.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InfoMallWebService.Controllers
{
    public class ContentForMallsController : Controller
    {
        private readonly IContentForMallRepository _con;
        private readonly ApplicationDbContext _ctx;
        public ContentForMallsController(IContentForMallRepository content, ApplicationDbContext context)
        {
            _con = content;
            _ctx = context;
        }
        // GET: ContentsForMalls
        public async Task<IActionResult> Index()
        {
            var model = await _con.GetAllContents();
            return View(model);
        }

        // GET: ContentsForMalls/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _con.GetContentByID(id, true);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        
        // GET: ContentsForMalls/Create
        public IActionResult Create()
        {
            ViewData["Category"] = new SelectList(_ctx.CategoriesForInformation, "CategoryId", "CategoryName");
            return View();
        }

        // POST: ContentsForMalls/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ContentForMallDto content)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                await _con.AddContent(content);
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: ContentsForMalls/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _con.GetContentByID(id, false);
            if (model == null)
            {
                return NotFound();
            }
            ViewData["Category"] = new SelectList(_ctx.CategoriesForInformation, "CategoryId", "CategoryName");
            return View(model);
        }

        // POST: ContentsForMalls/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ContentForMallDto content)
        {
            if (id != content.ContentId)
            {
                return RedirectToAction("Error", "Home");
            }
            if (!ModelState.IsValid)
            {
                return View("Edit", new { id });
            }
            try
            {
                await _con.UpdateContentWithID(content);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: ContentsForMalls/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _con.GetContentByID(id, false);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: ContentsForMalls/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id, ContentForMallDto content)
        {
            if (id != content.ContentId)
            {
                return RedirectToAction("Error", "Home");
            }
            if (!ModelState.IsValid)
            {
                return View("Delete", new { id });
            }
            try
            {
                _con.DeleteContentWithID(content);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

InfoMallWebService/Views/ContentForMalls/Create.cshtml
@model InfoMallWebService.Dtos.ContentForMallDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ContentForMallDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ContentMallPosition" class="control-label"></label>
                <input asp-for="ContentMallPosition" class="form-control" />
                <span asp-validation-for="ContentMallPosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <input asp-for="LongDescription" class="form-control" />
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ShowOnHome" /> @Html.DisplayNameFor(model => model.ShowOnHome)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category Name</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Category"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoMallWebService/Views/ContentForMalls/Delete.cshtml
@model InfoMallWebService.Dtos.ContentForMallDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ContentForMallDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePosted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfViews)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfViews)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContentMallPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContentMallPosition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LongDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowOnHome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowOnHome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OldImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OldImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@Model.ContentId">
        <input type="hidden" name="ImagesToDelete"/>
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InfoMallWebService/Views/ContentForMalls/Details.cshtml
@model InfoMallWebService.Dtos.ContentForMallDto


@inject ICategoryForInfoRepository Categories

@{
    ViewData["Title"] = "Details";
    List<ContentForMall> contentsTrending = new List<ContentForMall>();
    List<ContentForMall> contentsRecent = new List<ContentForMall>();
    var cats = await Categories.GetAllCategories(true);
    var otherContents = await Categories.GetCategoryById(Model.CategoryId, true);
}



<!-- single -->
<section class="banner-bottom py-5">
    <div class="container py-xl-5 py-lg-3">
        <div class="inner-sec">
            <div class="row">
                <!-- left side -->
                <div class="col-lg-8 left-blog-info text-left no-padding-left-blog">
                    <div class="blog-grid-top">
                        <h2 class="col-md-12 blog-h-font mb-3">@Model.Title</h2>
                        <div class="b-grid-top">
                            <div class="blog_info_left_grid padding-left-15">
                                <a>
                                    <img src="~/@Model.OldImage" alt="@Model.Title" class="img-fluid" />

                                </a>
                            </div>
                        </div>

                        <h3 class="padding-left-15">
                            @Model.ShortDescription
                        </h3>
                        <div class="col-md-12">
                            @Html.Raw(Model.LongDescription)
                        </div>
                    </div>
                    
                    @foreach (var content in otherContents.ContentsForInformation)
                    {
                        if (content.CategoryForInformationId == Model.CategoryId && content.NumberOfViews > 2)
                        {
                            contentsTrending.Add(content);
                        }
                        if (content.CategoryForInformationId == Model.CategoryId && DateTime.Now - content.DatePosted <= TimeSpan.FromDays(2))
                        {
                            contentsRecent.Add(content);
                        }

                    }

                </div>
                <!-- //left side -->
                <!-- right side -->
                <aside class="col-lg-4 right-blog-con text-right">
                    <div class="right-blog-info text-left">

                        <div class="tech-btm">
                            <h4>Categories</h4>
                            <ul class="list-group single">
                                @foreach (var category in cats)
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a asp-action="Details" asp-controller="CategoryForInfos" asp-route-id="@category.CategoryId">@category.CategoryName</a>
                                        <span class="badge badge-primary badge-pill">@category.ContentsForInformation.Count().ToString()</span>
                                    </li>
                                }
                            </ul>
                        </div>
                        <div class="tech-btm">
                            <h4>Top stories of the week</h4>
                            @foreach (var content in contentsTrending)
                            {
                                <div class="blog-grids row mb-3">
                                    <div class="col-md-5 blog-grid-left">
                                        <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                            <img src="~/@content.ImagePath" class="img-fluid rounded" alt="@content.ImagePath">
                                        </a>
                                    </div>
                                    <div class="col-md-7 blog-grid-right">
                                        <h5>
                                            <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                @content.ShortDescription
                                            </a>

                                        </h5>
                                        <div class="sub-meta">
                                            <span>
                                                <i class="far fa-clock"></i> @content.DatePosted.ToLongDateString()
                                            </span>
                                        </div>
                                    </div>

                                </div>
                            }


                        </div>

                        <div class="single-gd tech-btm">
                            <h4>Recent Post</h4>
                            <div class="blog-grids">
                                @foreach (var content in contentsRecent)
                                {
                                    <div class="blog-grids row mb-3">
                                        <div class="col-md-5 blog-grid-left">
                                            <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                <img src="~/@content.ImagePath" class="img-fluid rounded" alt="@content.ImagePath">
                                            </a>
                                        </div>
                                        <div class="col-md-7 blog-grid-right">
                                            <h5>
                                                <a asp-action="Details" asp-controller="ContentForMalls" asp-route-id="@content.ContentId" class="text-danger">
                                                    @content.ShortDescription
                                                </a>

                                            </h5>
                                            <div class="sub-meta">
                                                <span>
                                                    <i class="far fa-clock"></i> @content.DatePosted.ToShortDateString()
                                                </span>
                                            </div>
                                        </div>

                                    </div>
                                }
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                </aside>
                <!-- //right side -->
            </div>

        </div>
    </div>
</section>
<!-- //single -->

InfoMallWebService/Views/ContentForMalls/Edit.cshtml
@model InfoMallWebService.Dtos.ContentForMallDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ContentForMallDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.ContentId" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContentId"/>
            <input type="hidden" asp-for="OldImage"/>
            <div class="form-group">
                <label asp-for="ContentMallPosition" class="control-label"></label>
                <input asp-for="ContentMallPosition" class="form-control" />
                <span asp-validation-for="ContentMallPosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <input asp-for="LongDescription" class="form-control" />
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ShowOnHome" /> @Html.DisplayNameFor(model => model.ShowOnHome)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label">Replace existing image</label>
                <input asp-for="File" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category Name</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Category"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoMallWebService/Views/ContentForMalls/Index.cshtml
@model IEnumerable<InfoMallWebService.Dtos.ContentForMallDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoOfViews)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContentMallPosition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LongDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShowOnHome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OldImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DatePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfViews)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContentMallPosition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LongDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShowOnHome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OldImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ContentId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ContentId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ContentId })
            </td>
        </tr>
}
    </tbody>
</table>